import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { jsPDF } from 'jspdf';
import { getHistory } from '../api/client';

export default function ThreatReport() {
  const [selectedScans, setSelectedScans] = useState(new Set());
  
  const { data: history = [], isLoading } = useQuery({
    queryKey: ['history'],
    queryFn: getHistory,
    refetchInterval: 10000,
  });

  const toggleSelect = (idx) => {
    const newSelected = new Set(selectedScans);
    if (newSelected.has(idx)) {
      newSelected.delete(idx);
    } else {
      newSelected.add(idx);
    }
    setSelectedScans(newSelected);
  };

  const toggleAll = () => {
    if (selectedScans.size === history.length) {
      setSelectedScans(new Set());
    } else {
      setSelectedScans(new Set(history.map((_, i) => i)));
    }
  };

  const generateReport = () => {
    if (selectedScans.size === 0) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text('PhishGuard Threat Report', 14, 22);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Total Scans Included: ${selectedScans.size}`, 14, 36);

    doc.setDrawColor(203, 213, 225); // slate-300
    doc.line(14, 42, pageWidth - 14, 42);

    let yPos = 50;
    
    const scansToReport = Array.from(selectedScans).map(idx => history[idx]).sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

    scansToReport.forEach((scan, index) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      // Scan header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      
      const title = scan.url.length > 60 ? scan.url.substring(0, 60) + '...' : scan.url;
      doc.text(`URL: ${title}`, 14, yPos);
      
      yPos += 8;
      
      // Details
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      
      const isHarmful = ['phishing', 'malware'].includes(scan.label);
      if (isHarmful) doc.setTextColor(220, 38, 38); // red-600
      else if (scan.label === 'defacement') doc.setTextColor(202, 138, 4); // yellow-600
      else doc.setTextColor(22, 163, 74); // green-600
      
      doc.text(`Classification: ${scan.label === 'benign' ? 'SAFE' : scan.label.toUpperCase()}`, 14, yPos);
      
      doc.setTextColor(71, 85, 105); // slate-600
      doc.text(`Risk Score: ${(scan.risk_score * 100).toFixed(1)}/100`, 80, yPos);
      doc.text(`Confidence: ${(scan.confidence * 100).toFixed(1)}%`, 140, yPos);
      
      yPos += 6;
      doc.text(`Date: ${new Date(scan.timestamp).toLocaleString()}`, 14, yPos);
      
      // CTI Summary
      let ctiSummary = [];
      if (scan.cti?.virustotal?.malicious > 0) ctiSummary.push(`VT Malicious: ${scan.cti.virustotal.malicious}`);
      if (scan.cti?.urlhaus?.threat) ctiSummary.push(`URLHaus: ${scan.cti.urlhaus.threat}`);
      if (scan.is_obfuscated) ctiSummary.push('Obfuscation Detected');
      if (scan.typosquat_matches?.length > 0) ctiSummary.push(`Typosquat: ${scan.typosquat_matches.join(', ')}`);
      
      yPos += 6;
      if (ctiSummary.length > 0) {
         doc.text(`Threat Intel: ${ctiSummary.join(' | ')}`, 14, yPos);
      } else {
         doc.text('Threat Intel: No significant findings', 14, yPos);
      }

      yPos += 12;
      doc.setDrawColor(226, 232, 240); // slate-200
      doc.line(14, yPos - 6, pageWidth - 14, yPos - 6);
    });

    // Footer
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text('Generated by PhishGuard', 14, doc.internal.pageSize.getHeight() - 10);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, doc.internal.pageSize.getHeight() - 10);
    }

    doc.save(`phishguard-report-${Date.now()}.pdf`);
  };

  if (isLoading) return <div className="text-slate-400 text-center py-8">Loading history...</div>;

  return (
    <div className="space-y-6">
      <div className="bg-[#1e293b] p-6 rounded-xl border border-slate-700/50 shadow-sm flex flex-col sm:flex-row justify-between items-center gap-4">
        <div>
          <h2 className="text-lg font-semibold text-white">Generate Threat Report</h2>
          <p className="text-slate-400 text-sm mt-1">Select scans from the history below to include in a PDF report.</p>
        </div>
        <button
          onClick={generateReport}
          disabled={selectedScans.size === 0}
          className="bg-[#38bdf8] hover:bg-[#0284c7] text-white px-6 py-2.5 rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap flex items-center gap-2"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
          Export PDF ({selectedScans.size})
        </button>
      </div>

      <div className="bg-[#1e293b] rounded-xl border border-slate-700/50 shadow-sm overflow-hidden">
        <div className="overflow-x-auto max-h-[600px] overflow-y-auto">
          <table className="w-full text-left text-sm whitespace-nowrap">
            <thead className="bg-slate-800/90 text-slate-400 sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-6 py-4">
                  <input
                    type="checkbox"
                    checked={history.length > 0 && selectedScans.size === history.length}
                    onChange={toggleAll}
                    className="w-4 h-4 rounded border-slate-600 bg-slate-700 text-[#38bdf8] focus:ring-[#38bdf8] focus:ring-offset-slate-800"
                  />
                </th>
                <th className="px-6 py-4 font-medium">Date</th>
                <th className="px-6 py-4 font-medium w-full">URL</th>
                <th className="px-6 py-4 font-medium">Classification</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-700/50">
              {history.map((scan, idx) => (
                <tr key={idx} className="hover:bg-slate-800/50 transition-colors">
                  <td className="px-6 py-3">
                    <input
                      type="checkbox"
                      checked={selectedScans.has(idx)}
                      onChange={() => toggleSelect(idx)}
                      className="w-4 h-4 rounded border-slate-600 bg-slate-700 text-[#38bdf8] focus:ring-[#38bdf8] focus:ring-offset-slate-800"
                    />
                  </td>
                  <td className="px-6 py-3 text-slate-400">
                    {new Date(scan.timestamp).toLocaleString()}
                  </td>
                  <td className="px-6 py-3 text-slate-200 font-mono text-xs truncate max-w-[200px] sm:max-w-md lg:max-w-xl">
                    {scan.url}
                  </td>
                  <td className="px-6 py-3 uppercase text-xs font-semibold text-slate-300">
                    <span className={`px-2 py-1 rounded-full ${
                      scan.label === 'phishing' || scan.label === 'malware' ? 'bg-red-500/10 text-red-400' :
                      scan.label === 'defacement' ? 'bg-yellow-500/10 text-yellow-400' :
                      'bg-emerald-500/10 text-emerald-400'
                    }`}>
                      {scan.label === 'benign' ? 'Safe' : scan.label}
                    </span>
                  </td>
                </tr>
              ))}
              {history.length === 0 && (
                <tr>
                  <td colSpan="4" className="px-6 py-8 text-center text-slate-500">
                    No scan history available for reporting.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
